function f = pendulum_sys(t,in2)
%PENDULUM_SYS
%    F = PENDULUM_SYS(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    05-Sep-2016 19:29:01

q1 = in2(1,:);
q2 = in2(2,:);
q_dot1 = in2(3,:);
q_dot2 = in2(4,:);
f = [q_dot1;q_dot2;sin(q1+q2).*(-1.96e2./2.5e1)-sin(q1).*(5.88e2./2.5e1)+q_dot2.^2.*sin(q2).*(2.0./5.0);0.0];
