function f = ball_sys(t,in2)
%BALL_SYS
%    F = BALL_SYS(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Sep-2016 11:50:03

q_dot1 = in2(3,:);
q_dot2 = in2(4,:);
f = [q_dot1;q_dot2;0.0;-4.9e1./5.0];
