function [value,isterminal,direction] = ground_event(t,in2)
%GROUND_EVENT
%    [VALUE,ISTERMINAL,DIRECTION] = GROUND_EVENT(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    07-Sep-2016 11:50:03

q2 = in2(2,:);
value = q2-1.0./2.0e1;
if nargout > 1
    isterminal = 1.0;
end
if nargout > 2
    direction = -1.0;
end
